Vita - Bestiar
fantasion/fantasion pull request #144
Opened 2022-03-31 17:42 UTC by vitvrs

Bestiář se zobrazuje na .../bestar/

2022-04-01 21:14 UTC, just-paja commented
@vitvrs, it does not build. Please fix.

2022-04-01 21:57 UTC, vitvrs commented
> @vitvrs, it does not build. Please fix.

@just-paja fixed ;)

2022-04-02 00:07 UTC, just-paja requested changes
Looks fine, just clean the code please.

I noticed the ContactForm component is unused at the moment and assume that's work in progress. Acceptable to merge given project's status.

2022-04-02 00:07 UTC, just-paja commented on package.json
> +    "download": "^8.0.0",
We shouldn't pull in stuff we don't need. Please remove this extra dependency

2022-04-02 00:07 UTC, just-paja commented on packages/fantasion-web/components/contact.module.scss
> +@import '../styles/variables.scss';
This CSS module is empty. Please remove it, so we don't pollute the codebase.

2022-04-02 00:07 UTC, just-paja commented on packages/fantasion-web/components/monsters.js
> +    // subTitle={monster.species}
Dead code. Please remove.

2022-04-02 00:07 UTC, just-paja commented on packages/fantasion-web/components/monsters.module.scss
> +@keyframes appear {
Let's keep this, but remember that the code needs to be deduplicated.

2022-04-02 00:07 UTC, just-paja commented on packages/fantasion-web/pages/contact.js
> +// import { ContactForm } from '../components/contact'
Dead code. Please remove.

2022-04-02 00:07 UTC, just-paja commented on packages/fantasion-web/pages/contact.js
> +// import { Heading } from '../components/media'
Dead code. Please remove.

2022-04-02 00:07 UTC, just-paja commented on packages/fantasion-web/pages/contact.js
> +            <ContactForm /> */}
Dead code. Please remove.

2022-04-02 00:44 UTC, just-paja approved these changes

2022-04-02 00:51 UTC, merged